# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_auto_20171016_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
