# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_auto_20171017_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='laudo',
            field=models.TextField(),
        ),
    ]
